### ISSUE TITLE
Merge with the other awesome-markdown

### ISSUE THREAD

**Issue by aloisdg** [writekit/awesome-markdown#4]
Hello,

I would propose a merge between this project and [the one](https://github.com/mashk/awesome-markdown) by @mashk.
You are both working on exactly the same project.
What do you think?

Cheers.

**Comment by geraldb** [comment]
Great idea. Why not send in a pull request? Cheers.

**Comment by aloisdg** [comment]
Why should we keep this one? Shouldn't we wait for @mashk's opinion?
